[package]
name = "tsk"
version = "0.0.1"
authors = ["forensicmatt <matthew.seyer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"

[build-dependencies]
bindgen = "0.53.1"